### ISSUE TITLE
Xamarin.Android build fails

### ISSUE THREAD

**Issue by nielscup** [MicrosoftDocs/pipelines-xamarin#5]
Building a Xamarin.Android app results in the following error: 
`Project file could not be imported, it was being imported by /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: The attribute "CopyToOutputDirectory" in element <None> is unrecognized.`

Below is my YML. Any ideas?

```
pool:
  vmImage: 'macOS-10.15'

  variables:
    buildConfiguration: 'Release'
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
    
steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildVersionOption: '16.0'

- task: AndroidSigning@3
  inputs:
    apksign: false
    zipalign: false
    apkFiles: '$(outputDirectory)/*.apk'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(outputDirectory)/*.apk'
```
